import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Componets/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Restaurant Booking System",
  description: "Generated by Soham Chogale...",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" container mx-auto">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
